server:
  port: 8080
spring:
  datasource:
    url: jdbc:mysql://scurl/scdev
    user: root
    password: scpsw
  h2:
    console:
      enabled: true
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
