server:
  port: 8080
spring:
  datasource:
    url: jdbc:mysql://scurl/scdev
    username: root
    password: scpsw
  #    url: jdbc:h2:file:./h2/org
  h2:
    console:
      enabled: true
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update

  flyway.baselineOnMigrate: true
